import setuptools

if __name__ == "__main__":
    setuptools.setup(
        name="ocvbot",
        version="0.1",
        packages=["ocvbot"],
        install_requires=[
            "Babel",
            "Jinja2",
            "Pillow",
            "PyYAML",
            "Pygments",
            "alabaster",
            "colorama",
            "commonmark",
            "cython",
            "docutils<0.18,>=0.14",
            "imagesize",
            "keyboard",
            "lxml",
            "numpy",
            "opencv-python",
            "packaging",
            "psutil",
            "pyautogui",
            "pyclick",
            "pytest",
            "pytz",
            "recommonmark",
            "requests",
            "scikit-build",
            "setuptools",
            "snowballstemmer",
            "wheel",
        ],
        tests_requires=[
            "pytest",
            "psutil",
        ],
        entry_points={
            "distutils.commands": [
                "ocvbot = ocvbot:main.py",
            ],
        },
        author="T. Austin Kelley",
        author_email="hxyz@protonmail.com",
        description="The OldSchool Runescape Computer Vision Bot",
        license="MIT",
    )
